package com.example.calculateservice.swagger.server.api;

/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.56).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

import com.example.calculateservice.swagger.client.abs.model.FinancialProductsResponseDto;
import com.example.calculateservice.swagger.server.model.ApiErrorResponseDto;
import java.math.BigDecimal;
import com.example.calculateservice.swagger.server.model.CalculatedProductsResponseDto;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Validated
public interface FinancialProductsApi {

    Logger log = LoggerFactory.getLogger(FinancialProductsApi.class);

    Optional<ObjectMapper> getObjectMapper();

    Optional<HttpServletRequest> getRequest();



    @Operation(summary = "Выборка финансовых продуктов", description = "Запрос на получение продуктов по заданными параметрам", security = {
            @SecurityRequirement(name = "BearerAuth")    }, tags={  })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = CalculatedProductsResponseDto.class))),

            @ApiResponse(responseCode = "400", description = "Bad request", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

            @ApiResponse(responseCode = "404", description = "Not Found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

            @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

            @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))) })
    @RequestMapping(value = "/financial-products",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<CalculatedProductsResponseDto> financialProductsGet(@NotNull @DecimalMin("1")@Parameter(in = ParameterIn.QUERY, description = "Сумма вклада" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "sum", required = true) BigDecimal sum
            , @NotNull @Parameter(in = ParameterIn.QUERY, description = "Тип клиента, которому доступен вклад" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "categories", required = true) List<String> categories
            , @NotNull @Pattern(regexp="^[A-Z]{3}$") @Parameter(in = ParameterIn.QUERY, description = "Валюта вклада" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "currency", required = true) String currency
            , @Parameter(in = ParameterIn.QUERY, description = "Срок на который вклад можно открыть" ,schema=@Schema()) @Valid @RequestParam(value = "periods", required = false) List<Integer> periods
            , @Parameter(in = ParameterIn.QUERY, description = "Возможность пополнения с вклада" ,schema=@Schema()) @Valid @RequestParam(value = "canDeposit", required = false) Boolean canDeposit
            , @Parameter(in = ParameterIn.QUERY, description = "Возможность снятия с вклада" ,schema=@Schema()) @Valid @RequestParam(value = "canWithdrawal", required = false) Boolean canWithdrawal
            , @Parameter(in = ParameterIn.QUERY, description = "Есть ли капитализация" ,schema=@Schema()) @Valid @RequestParam(value = "capitalizationToSameAccount", required = false) Boolean capitalizationToSameAccount
            , @Parameter(in = ParameterIn.QUERY, description = "Периодичность выплат вклада" ,schema=@Schema()) @Valid @RequestParam(value = "capitalizationPeriods", required = false) List<String> capitalizationPeriods
    );

    ResponseEntity<FinancialProductsResponseDto> financialProductsGet();
}


