package com.example.calculateservice.swagger.client.abs.api;

/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.56).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

import com.example.calculateservice.swagger.client.abs.model.ApiErrorResponseDto;
import com.example.calculateservice.swagger.client.abs.model.ClientDto;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Validated
public interface ClientsApi {

    Logger log = LoggerFactory.getLogger(ClientsApi.class);

    Optional<ObjectMapper> getObjectMapper();

    Optional<HttpServletRequest> getRequest();



    @Operation(summary = "Метод идентификации клиента по пасспорту", description = "", security = {
            @SecurityRequirement(name = "BearerAuth")    }, tags={ "ABS" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ с найденным клиентом", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDto.class))),

            @ApiResponse(responseCode = "400", description = "Bad Request", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

            @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

            @ApiResponse(responseCode = "404", description = "Not Found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))) })
    @RequestMapping(value = "/clients",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<ClientDto> getClient(@NotNull @Pattern(regexp="^[0-9]+$") @Size(min=10,max=10) @Parameter(in = ParameterIn.QUERY, description = "Данные паспорта (серия номер) для идентификации клиента" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "passport", required = true) String passport
    );

}


